- name: Ensure rustup is not installed
  shell: command -v rustup
  register: rustup_exists
  ignore_errors: yes
  become: true

- name: Get rustup install script
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: install rust/cargo
  shell: /tmp/sh.rustup.rs -y
  become: true
