- name: Ensure bash installed pacman
  community.general.pacman:
    name: bash
    state: present

- name: Ensure config dir
  ansible.builtin.file:
    name: "{{ host_user_config }}/bash"
    state: directory
    mode: '0755'

- name: Provide bashrc
  ansible.posix.synchronize:
    src: .bashrc
    dest: '{{ host_user_home }}'
  become: true

- name: Provide autoload source scripts
  ansible.posix.synchronize:
    src: autoload
    dest: '{{ host_user_config }}/bash'
  become: true

- name: Ensure secrets dir
  ansible.builtin.file:
    name: "{{ host_user_config }}/bash/secrets"
    state: directory
    mode: '0755'

- name: Resolve local secrets scripts
  delegate_to: localhost
  ansible.builtin.stat:
    path: '{{ source_secrets_dir }}/bash'
  register: secrets

- name: Provide secrets source scripts
  ansible.posix.synchronize:
    src: '{{ source_secrets_dir }}/bash/'
    dest: '{{ host_user_config }}/bash/secrets'
  become: true
  when: secrets.stat.exists
