- name: Setup Arch distribution
  hosts: all
  module_defaults:
    ansible.builtin.file:
      owner: '{{ host_user }}'
      group: '{{ host_user }}'
      mode: '0644'
    ansible.builtin.copy:
      owner: '{{ host_user }}'
      group: '{{ host_user }}'
  roles:
    - kakoune
    - alacritty
    - bash
    - docker
    - rust
