- hosts: all
  module_defaults:
    file:
      owner: '{{ host_user }}'
      group: '{{ host_user }}'
    copy:
      owner: '{{ host_user }}'
      group: '{{ host_user }}'
  roles:
    - kakoune
    - alacritty
    - bash
