- name: Add user group
  group:
    name: '{{ host_group }}'
    gid: 1000
    state: present

- name: Add user
  user:
    name: '{{ host_user }}'
    uid: 1000
    groups: 'wheel,{{ host_group }}'
    generate_ssh_key: yes
    ssh_key_type: ed25519
    password: 12345
