- name: Install kakoune pacman
  community.general.pacman:
    name: kakoune
    state: present

- name: Provide configuration
  ansible.posix.synchronize:
    src: kak
    dest: '{{ host_user_config }}'
  become: true

- name: Provide kak-lsp config
  ansible.posix.synchronize:
    src: kak-lsp
    dest: '{{ host_user_config }}'
  become: true

- name: Ensure kakoune plugins directory
  ansible.builtin.file:
    name: '{{ host_user_config }}/kak/plugins/'
    state: directory
    mode: '0755'

- name: Ensure kakoune autoload directory
  ansible.builtin.file:
    name: '{{ host_user_config }}/kak/autoload/'
    state: directory
    mode: '0755'

- name: Default autoload link
  ansible.builtin.file:
    src: /usr/share/kak/autoload
    dest: '{{ host_user_config }}/kak/autoload/01-default'
    state: link

- name: Fetch smarttab
  ansible.builtin.git:
    repo: https://github.com/andreyorst/smarttab.kak
    dest: '{{ host_user_config }}/kak/plugins/smarttab'
    version: 86ac6599b13617ff938905ba4cdd8225d7eb6a2e
    depth: 1
  become: true

- name: Smarttab autoload link
  ansible.builtin.file:
    src: '{{ host_user_config }}/kak/plugins/smarttab/rc/smarttab.kak'
    dest: '{{ host_user_config }}/kak/autoload/smarttab.kak'
    state: link

- name: Install kak-lsp pacman
  community.general.pacman:
    name: kak-lsp
    state: present

- name: Autoload kak-lsp
  ansible.builtin.file:
    src: /usr/share/kak-lsp/rc/lsp.kak
    dest: /usr/share/kak/autoload/kak-lsp.kak
    owner: root
    group: root
    state: link
    mode: '0644'

# - name: Permissions for kak-lsp script
#   ansible.builtin.file:
#     path: /usr/share/kak-lsp/rc/lsp.kak
#     mode: '0644'

- name: Provide kk wrapper
  ansible.posix.synchronize:
    src: kk.sh
    dest: '{{ host_local_bin }}/kk'
  become: true

- name: Permissions for kk wrapper
  ansible.builtin.file:
    path: '{{ host_local_bin }}/kk'
    mode: '0755'
