set -add global ui_options terminal_enable_mouse=false

cursorline

hook global BufOpenFile .* expandtab
hook global BufNewFile .* expandtab

hook global WinSetOption filetype=(makefile|gas|bash|lisp|go) %{
    set buffer tabstop 4
    noexpandtab
}

hook global WinSetOption filetype=(typescript|javascript|html|css|php|json|xml|yaml) %{
    set buffer tabstop 2
    set buffer indentwidth 2
}

set-option global scrolloff 8,15

define-command git_blame_show %{ evaluate-commands git show %sh{
    git blame -lL$kak_cursor_line,$kak_cursor_line $kak_bufname | cut -d' ' -f1
}} -hidden
