# Miscellaneous devtools which need no configuration

- name: Install misc devtools pacman
  community.general.pacman:
    name:
      - qemu-system-x86
      - qemu-tools
      - apptainer
    state: present

- name: Install modern unix tools
  community.general.pacman:
    name:
      - ripgrep
      - fzf
      - fff
    state: present

- name: Install networking tools
  community.general.pacman:
    name:
      - iproute2
      - networkmanager

- name: Enable network manager service
  ansible.builtin.service:
    name: NetworkManager
    enabled: true

- name: Install python packages pacman
  community.general.pacman:
    name:
      - python
      - python-numpy
      - python-matplotlib
      - jupyterlab
      - python-requests
    state: present
