- name: Install docker pacman
  community.general.pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: Enable docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Pull debian docker image
  community.docker.docker_image:
    name: 'debian:bookworm'
    source: pull

- name: Pull alpine docker image
  community.docker.docker_image:
    name: 'alpine:latest'
    source: pull

- name: Add docker user group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    append: true
    name: '{{ host_user }}'
    groups: docker
