- name: Install base packages
  community.general.pacman:
    name:
      - git
      - rsync
      - base-devel
      - sudo

- name: Setup user
  ansible.builtin.include_tasks: user.yml

- name: Provide ssh config and keys
  ansible.builtin.include_tasks: ssh.yml
