- name: Provide config
  ansible.posix.synchronize:
    src: ssh/
    dest: '{{ host_user_home }}/.ssh'
  become: true

- name: Provide private ssh key
  ansible.builtin.copy:
    src: '{{ source_secrets_dir }}/ssh/id_ed25519'
    dest: '{{ host_user_home }}/.ssh/'
    mode: '0600'

- name: Provide public ssh key
  ansible.builtin.copy:
    src: '{{ source_secrets_dir }}/ssh/id_ed25519.pub'
    dest: '{{ host_user_home }}/.ssh/'
    mode: '0644'
