- name: Add user group
  ansible.builtin.group:
    name: '{{ host_group }}'
    gid: 1000
    state: present

- name: Add wheel group
  ansible.builtin.group:
    name: wheel
    state: present

- name: Allow sudo for wheel group
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'

- name: Add user
  ansible.builtin.user:
    name: '{{ host_user }}'
    password: "{{ host_user_passwd | password_hash('sha512') }}"
    uid: 1000
    groups: 'wheel, {{ host_group }}'
    append: true
