- name: Install alacritty pacman
  community.general.pacman:
    name: alacritty
    state: latest

- name: Ensure config directories
  ansible.builtin.file:
    name: '{{ host_user_config }}/alacritty'
    state: directory
    mode: '0755'

- name: Render config config
  ansible.builtin.template:
    src: alacritty.yml.j2
    dest: '{{ host_user_config }}/alacritty/alacritty.yml'
    mode: '0644'

- name: Provode themes
  ansible.posix.synchronize:
    src: themes
    dest: '{{ host_user_config }}/alacritty/themes/'
  become: true
