- name: Add AUR builder group
  ansible.builtin.group:
    name: aur_builder
    state: present

- name: Add AUR builder user
  ansible.builtin.user:
   name: aur_builder
   group: aur_builder

- name: Add aur_builder to sudoers
  ansible.builtin.lineinfile:
   path: /etc/sudoers.d/11-install-aur_builder
   line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
   create: yes
   mode: 0644
   validate: 'visudo -cf %s'

- name: Install yay AUR
  vars:
    ansible_become_user: aur_builder
  kewlfft.aur.aur:
    name: yay
    state: present
  become: true
