# Miscellaneous devtools which need no configuration

- name: Install misc devtools pacman
  community.general.pacman:
    name:
      - qemu-system-x86
      - qemu-tools
      - apptainer
      - strace
      - gdb
    state: present

- name: Install modern unix tools
  community.general.pacman:
    name:
      - ripgrep
      - fzf
      - fff
    state: present

- name: Install networking tools
  community.general.pacman:
    name:
      - iproute2
      - networkmanager
      - netcat

- name: Enable network manager service
  ansible.builtin.service:
    name: NetworkManager
    enabled: true

- name: Install python packages pacman
  community.general.pacman:
    name:
      - python
      - python-setuptools
      - python-lsp-server
      - python-pip
      - python-numpy
      - python-matplotlib
      - jupyterlab
      - python-requests
    state: present

- name: Install golang packages pacman
  community.general.pacman:
    name:
      - go
      - gopls
      - go-tools
    state: present

- name: Install C/C++ tools
  community.general.pacman:
    name:
      - clang
      - cmake
      - ninja
      - make
      - valgrind
    state: present

- name: Add AUR user
 ansible.builtin.user:
   name: aur_builder
   group: wheel

- name: Add aur_builder to sudoers
 ansible.builtin.lineinfile:
   path: /etc/sudoers.d/11-install-aur_builder
   line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
   create: yes
   mode: 0644
   validate: 'visudo -cf %s'

- name: Install CLI graphics tools
  community.general.pacman:
    name:
      - imagemagick
      - ffmpeg
      - libheif
    state: present

- name: Install yay AUR
  vars:
    ansible_become_user: aur_builder
  kewlfft.aur.aur:
    name: yay
    state: present
  become: true
