- name: Install networking tools
  community.general.pacman:
    name:
      - iproute2
      - networkmanager
      - netcat
      - dhclient
      - openssh
      - net-tools
      - ufw

- name: Enable ufw
  community.general.ufw:
    state: enabled
    policy: allow
